### ISSUE TITLE
客户端报错 something goes wrong with reason:something goes wrong with channel

### ISSUE THREAD

**Issue by MrWangwj** [CanalClient/canal-go#2]
错误信息
```
panic: something goes wrong with reason:something goes wrong with channel:[id: 0x7f903ed0, /172.25.56.90:52211 => /10.179.25.89:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: ClientIdentity:ClientIdentity[destination=example,clientId=1001,filter=<null>] should subscribe first


goroutine 1 [running]:
github.com/CanalClient/canal-go/client.(*SimpleCanalConnector).receiveMessages(0xc0000f3f00, 0x2e)
	/Users/test/go/src/github.com/CanalClient/canal-go/client/SimpleCanalConnector.go:272 +0x838
github.com/CanalClient/canal-go/client.(*SimpleCanalConnector).GetWithOutAck(0xc0000f3f00, 0x3e8, 0x0, 0xc0000f3e14, 0x0)
	/Users/test/go/src/github.com/CanalClient/canal-go/client/SimpleCanalConnector.go:191 +0x2ec
github.com/CanalClient/canal-go/client.(*SimpleCanalConnector).Get(0xc0000f3f00, 0x3e8, 0x0, 0x0, 0x0)
	/Users/test/go/src/github.com/CanalClient/canal-go/client/SimpleCanalConnector.go:196 +0x47
main.main()
	/Users/test/go/src/server_cache/public/canal_client.go:21 +0x13a

Process finished with exit code 2
```
代码

```
func main()  {
	connector := client.NewSimpleCanalConnector("mc1.cn", 11111, "", "", "example", 60000, 60*60*1000)
	connector.Connect()

	fmt.Println("连接成功")
	for {
		message := connector.Get(1000, nil, nil)
		batchId := message.Id
		if batchId == -1 || len(message.Entries) <= 0 {
			time.Sleep(300 * time.Millisecond)
			fmt.Println("===没有数据了===")
			continue
		}

		printEntry(message.Entries)
	}
}

```
使用java客户端测试可以正常的获取binlog日志解析，环境是 centeros6.7+mysql5.7+go1.11

**Comment by WithLin** [comment]
代码的操作方式不对，应该 connector.Subscribe(".*\\\\..*") ，你可以去[samples](https://github.com/CanalClient/canal-go/blob/master/samples/main.go) 和用java的形式是一样的。
